### ISSUE TITLE
Determination of Scrolling Element is Wrong with Chrome 61 and later

### ISSUE THREAD

**Issue by dtapuska** [adobe/Spry#4]
Determining the scrolling element is wrong now that Chrome has changed to match other vendors and the specification.

The following code is in the repository:
var doc = (Spry.is.ie && strictm || Spry.is.mozilla)?
    source.ownerDocument.documentElement:source.ownerDocument.body;

An alternate implementation should be something like:
var doc;
if (source.ownerDocument.scrollingElement) {
  doc = source.ownerDocument.scrollingElement;
} else {
  doc = (Spry.is.ie && strictm || Spry.is.mozilla)?
    source.ownerDocument.documentElement:source.ownerDocument.body;
}

**Comment by filmaj** [comment]
Hello, sorry, but this project is no longer maintained and will be going into an archived state. If you wish to revive it, consider forking it!
