### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by filmaj** [adobe/Spry#5]
Hello @adobe/spry ,
My name is Fil and I’m from Adobe’s Open Source Office. I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project?

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html).

If no, is it OK if we archive this project? Or even delete it?

Thanks for any info.

-Fil

**Comment by ramines** [comment]
project need update

**Comment by Nelmedia** [comment]
I highly doubt so... Adobe has developed Spry for Dreamweaver and kept it for a couple of versions... Then they replaced it with jQuery and haven't updated it for years...

**Comment by filmaj** [comment]
It does indeed sound like this project is no longer maintained and there are no plans on keeping it up to date. I will close all issues and pull requests, update the README, and archive the project.
